version: "3"
services:
  example-application:
    image: eclipse-temurin:25.0.3_9-jre@sha256:6e9581a150f9ad80d9154f6c9dc4e5df0d4f5eb545e788340e2271e2fb5d3870
    network_mode: host
    volumes:
      - ./target/example-custom-buckets.jar:/example-custom-buckets.jar
    command:
      - /opt/java/openjdk/bin/java
      - -jar
      - /example-custom-buckets.jar
  prometheus:
    image: prom/prometheus:v3.14.0@sha256:5ce7540c3c00ef4ab0c9d2c995c6a5b9c421f44b4a115d97a2c7af3b1c21cbb0
    network_mode: host
    volumes:
      - ./docker-compose/prometheus.yml:/prometheus.yml
    command:
      - --enable-feature=native-histograms
      - --config.file=/prometheus.yml
  grafana:
    image: grafana/grafana:13.2.0@sha256:3fd54ae1214669f8355f065ec9f6445d5279a3d77095ab048ca045685272429b
    network_mode: host
    volumes:
      - ./docker-compose/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
      - ./docker-compose/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
      - ./docker-compose/grafana-dashboard-custom-buckets.json:/etc/grafana/grafana-dashboard-custom-buckets.json
