version: "3"
services:
  example-application:
    image: eclipse-temurin:25.0.3_9-jre@sha256:d0eb1b9018b3044da1b7346f39e945f71095749853d69a3aa16b8c99dad9bb45
    network_mode: host
    volumes:
      - ./target/example-custom-buckets.jar:/example-custom-buckets.jar
    command:
      - /opt/java/openjdk/bin/java
      - -jar
      - /example-custom-buckets.jar
  prometheus:
    image: prom/prometheus:v3.13.1@sha256:3c42b892cf723fa54d2f262c37a0e1f80aa8c8ddb1da7b9b0df9455a35a7f893
    network_mode: host
    volumes:
      - ./docker-compose/prometheus.yml:/prometheus.yml
    command:
      - --enable-feature=native-histograms
      - --config.file=/prometheus.yml
  grafana:
    image: grafana/grafana:13.1.0@sha256:121a7a9ece6dc10b969f1f96eed64b4f07dfac0d0b8abc070f7cb83bbde86f63
    network_mode: host
    volumes:
      - ./docker-compose/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
      - ./docker-compose/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
      - ./docker-compose/grafana-dashboard-custom-buckets.json:/etc/grafana/grafana-dashboard-custom-buckets.json
