version: "3"
services:
  prometheus-opentelemetry-example-app:
    image: openjdk:11.0.16-jre@sha256:356949c3125c4fa8104745e7ea92bd995da4567634e6599b470d2f972d13e0e2
    network_mode: host
    ports:
      - "5005:5005"
    volumes:
      - ./target/example-exporter-opentelemetry.jar:/example-exporter-opentelemetry.jar
    command:
      - java
      - -jar
      #- -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005
      - /example-exporter-opentelemetry.jar
  collector:
    image: otel/opentelemetry-collector-contrib:0.150.1@sha256:a516c26968aa1feb5e5fc0562e3338ea13755cb4f373603226bcc4e276374ad0
    network_mode: host
    volumes:
      - ./config/otelcol-config.yaml:/config.yaml
    command:
      - --config=file:/config.yaml
  prometheus:
    image: prom/prometheus:v3.11.2@sha256:5550dc63da361dc30f6fe02ac0e4dfc736ededfef3c8d12a634db04a67824d78
    network_mode: host
    volumes:
      - ./config/prometheus.yaml:/prometheus.yaml
    command:
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --web.enable-remote-write-receiver
      - --config.file=/prometheus.yaml
