version: "3"
services:
  prometheus-opentelemetry-example-app:
    image: openjdk:11.0.16-jre@sha256:356949c3125c4fa8104745e7ea92bd995da4567634e6599b470d2f972d13e0e2
    network_mode: host
    ports:
      - "5005:5005"
    volumes:
      - ./target/example-exporter-opentelemetry.jar:/example-exporter-opentelemetry.jar
    command:
      - java
      - -jar
      #- -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005
      - /example-exporter-opentelemetry.jar
  collector:
    image: otel/opentelemetry-collector-contrib:0.156.0@sha256:125bdbeb7590cc1952c5b3430ecf14063568980c2c93d5b38676cc0446ed8108
    network_mode: host
    volumes:
      - ./config/otelcol-config.yaml:/config.yaml
    command:
      - --config=file:/config.yaml
  prometheus:
    image: prom/prometheus:v3.13.1@sha256:3c42b892cf723fa54d2f262c37a0e1f80aa8c8ddb1da7b9b0df9455a35a7f893
    network_mode: host
    volumes:
      - ./config/prometheus.yaml:/prometheus.yaml
    command:
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --web.enable-remote-write-receiver
      - --config.file=/prometheus.yaml
