services:
  lgtm:
    image: ${LGTM_IMAGE:-docker.io/grafana/otel-lgtm:latest}
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
      - "3200:3200"
      - "4040:4040"
      - "9090:9090"
