version: 2
machine: true
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/circleci-java
    steps:
      - run:
          name: Install OpenJDK 17
          command: |
              sudo apt-get update && sudo apt-get install -y openjdk-17-jdk
              sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
              sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
              java -version
      - checkout
      - restore_cache:
          key: maven-dependencies-{{ checksum "pom.xml" }}
      - run: cd prometheus-metrics-shaded-dependencies && ../mvnw clean install && cd ..
      - run: ./mvnw clean install
      - run: ./mvnw javadoc:jar
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}
orbs:
  prometheus: prometheus/prometheus@0.16.0
