version: "3"
services:
  example-application:
    image: eclipse-temurin:25.0.3_9-jre@sha256:681c543d6f36c50f45e9b5226930a46203dcfa351d3670e9d0bdf0dabae53539
    network_mode: host
    volumes:
      - ./target/example-native-histogram.jar:/example-native-histogram.jar
    command:
      - /opt/java/openjdk/bin/java
      - -jar
      - /example-native-histogram.jar
  prometheus:
    image: prom/prometheus:v3.13.1@sha256:3c42b892cf723fa54d2f262c37a0e1f80aa8c8ddb1da7b9b0df9455a35a7f893
    network_mode: host
    volumes:
      - ./docker-compose/prometheus.yml:/prometheus.yml
    command:
      - --enable-feature=native-histograms
      - --config.file=/prometheus.yml
  grafana:
    image: grafana/grafana:13.1.1@sha256:1c1bd67c54c5fcf6e759897852b5a584191bd6796e8d328a5ace457799801261
    network_mode: host
    volumes:
      - ./docker-compose/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
      - ./docker-compose/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
      - ./docker-compose/grafana-dashboard-classic-histogram.json:/etc/grafana/grafana-dashboard-classic-histogram.json
      - ./docker-compose/grafana-dashboard-native-histogram.json:/etc/grafana/grafana-dashboard-native-histogram.json
