version: "3"
services:
  example-application:
    image: eclipse-temurin:25.0.3_9-jre@sha256:04262e8782d6b034ee5d7c1c5d4e8938fcf2063a76b4bfcd84e5d994d09c27bc
    network_mode: host
    volumes:
      - ./target/example-native-histogram.jar:/example-native-histogram.jar
    command:
      - /opt/java/openjdk/bin/java
      - -jar
      - /example-native-histogram.jar
  prometheus:
    image: prom/prometheus:v3.12.0@sha256:69f5241418838263316593f7274a304b095c40bcf22e57272865da91bd60a8ac
    network_mode: host
    volumes:
      - ./docker-compose/prometheus.yml:/prometheus.yml
    command:
      - --enable-feature=native-histograms
      - --config.file=/prometheus.yml
  grafana:
    image: grafana/grafana:13.0.1@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
    network_mode: host
    volumes:
      - ./docker-compose/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
      - ./docker-compose/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
      - ./docker-compose/grafana-dashboard-classic-histogram.json:/etc/grafana/grafana-dashboard-classic-histogram.json
      - ./docker-compose/grafana-dashboard-native-histogram.json:/etc/grafana/grafana-dashboard-native-histogram.json
