version: "3"
services:
  example-application:
    image: eclipse-temurin:25.0.3_9-jre@sha256:f19dbf0a22d0b3658fda48ce7d7181df05ad14bda151dd5ad12cc09d1451c70e
    network_mode: host
    volumes:
      - ./target/example-native-histogram.jar:/example-native-histogram.jar
    command:
      - /opt/java/openjdk/bin/java
      - -jar
      - /example-native-histogram.jar
  prometheus:
    image: prom/prometheus:v3.13.2@sha256:508729e0e2d18e11fd742a5a5ca70e557b940a93948c3c95fd0123a6fd538b69
    network_mode: host
    volumes:
      - ./docker-compose/prometheus.yml:/prometheus.yml
    command:
      - --enable-feature=native-histograms
      - --config.file=/prometheus.yml
  grafana:
    image: grafana/grafana:13.1.2@sha256:d177053ab62253815f130d81504f77063baf5fd4ca93299d6048453bd31e047a
    network_mode: host
    volumes:
      - ./docker-compose/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
      - ./docker-compose/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
      - ./docker-compose/grafana-dashboard-classic-histogram.json:/etc/grafana/grafana-dashboard-classic-histogram.json
      - ./docker-compose/grafana-dashboard-native-histogram.json:/etc/grafana/grafana-dashboard-native-histogram.json
