---
global:
  scrape_interval: 5s # very short interval for demo purposes

scrape_configs:
  - job_name: "demo"
    # this will make Prometheus scrape both, the native and the classic histogram.
    scrape_classic_histograms: true
    static_configs:
      - targets: ["localhost:9400"]
