version: "3"
services:
  hello-world-app:
    image: opentelemetry-java-agent
    build:
      context: .
      dockerfile_inline: |
        FROM openjdk:11-jre
        WORKDIR /
        RUN curl -sOL https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.30.0/opentelemetry-javaagent.jar
    network_mode: host
    volumes:
      - ./example-hello-world-app/target/example-hello-world-app.jar:/example-hello-world-app.jar
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    command:
      - java
      - -javaagent:/opentelemetry-javaagent.jar
      - -jar
      - /example-hello-world-app.jar
  greeting-service:
    # The opentelemetry-java-agent image is coming from the hello-world-up service above.
    image: opentelemetry-java-agent
    network_mode: host
    volumes:
      - ./example-greeting-service/target/example-greeting-service.jar:/example-greeting-service.jar
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    command:
      - java
      - -javaagent:/opentelemetry-javaagent.jar
      - -jar
      - /example-greeting-service.jar
  collector:
    image: otel/opentelemetry-collector-contrib:0.161.0@sha256:fd328de2552466ad78385e1b1289c3f2402b1c45f265b252aab1955b42845ac1
    network_mode: host
    volumes:
      - ./config/otelcol-config.yaml:/config.yaml
    command:
      - --config=file:/config.yaml
  prometheus:
    image: prom/prometheus:v3.15.0@sha256:efd719c99d83b060d9daefdcf00360461adf279f45ef5391f8d111892118753e
    network_mode: host
    volumes:
      - ./config/prometheus.yaml:/prometheus.yaml
    command:
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --config.file=/prometheus.yaml
  tempo:
    image: grafana/tempo:3.0.3@sha256:0296560ac66f8a3600d7fb3014a52c189d4d9c3549ad6ff441bf2409855d68d5
    network_mode: host
    volumes:
      - ./config/tempo-config.yaml:/config.yaml
    command:
      - --config.file=/config.yaml
  grafana:
    image: grafana/grafana:13.2.2@sha256:ac461fb352abc50da10a51c7d02462e9c05488f11f53f14b3ad79a8145f638a0
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
      - ./config/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
      - ./config/grafana-example-dashboard.json:/etc/grafana/example-dashboard.json
  k6:
    image: grafana/k6@sha256:e66db15b860113878fa74670e31f5e274830b7b6e42c8bff28b2f2d86a257603
    network_mode: host
    volumes:
      - ./config/k6-script.js:/k6-script.js
    command:
      - run
      - /k6-script.js
