version: "3"
services:
  hello-world-app:
    image: opentelemetry-java-agent
    build:
      context: .
      dockerfile_inline: |
        FROM openjdk:11-jre
        WORKDIR /
        RUN curl -sOL https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.30.0/opentelemetry-javaagent.jar
    network_mode: host
    volumes:
      - ./example-hello-world-app/target/example-hello-world-app.jar:/example-hello-world-app.jar
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    command:
      - java
      - -javaagent:/opentelemetry-javaagent.jar
      - -jar
      - /example-hello-world-app.jar
  greeting-service:
    # The opentelemetry-java-agent image is coming from the hello-world-up service above.
    image: opentelemetry-java-agent
    network_mode: host
    volumes:
      - ./example-greeting-service/target/example-greeting-service.jar:/example-greeting-service.jar
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    command:
      - java
      - -javaagent:/opentelemetry-javaagent.jar
      - -jar
      - /example-greeting-service.jar
  collector:
    image: otel/opentelemetry-collector-contrib:0.156.0@sha256:125bdbeb7590cc1952c5b3430ecf14063568980c2c93d5b38676cc0446ed8108
    network_mode: host
    volumes:
      - ./config/otelcol-config.yaml:/config.yaml
    command:
      - --config=file:/config.yaml
  prometheus:
    image: prom/prometheus:v3.13.1@sha256:3c42b892cf723fa54d2f262c37a0e1f80aa8c8ddb1da7b9b0df9455a35a7f893
    network_mode: host
    volumes:
      - ./config/prometheus.yaml:/prometheus.yaml
    command:
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --config.file=/prometheus.yaml
  tempo:
    image: grafana/tempo:3.0.2@sha256:cda87c212d8c584dc0b89e337e7ed648a5100feb657e5d528480ee4fa03dbbe3
    network_mode: host
    volumes:
      - ./config/tempo-config.yaml:/config.yaml
    command:
      - --config.file=/config.yaml
  grafana:
    image: grafana/grafana:13.1.0@sha256:121a7a9ece6dc10b969f1f96eed64b4f07dfac0d0b8abc070f7cb83bbde86f63
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
      - ./config/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
      - ./config/grafana-example-dashboard.json:/etc/grafana/example-dashboard.json
  k6:
    image: grafana/k6@sha256:e7eeddf1ce2361df6920d925297f487c0ba549c44be242c6a9c22f28d9b08efa
    network_mode: host
    volumes:
      - ./config/k6-script.js:/k6-script.js
    command:
      - run
      - /k6-script.js
