version: "3"
services:
  hello-world-app:
    image: opentelemetry-java-agent
    build:
      context: .
      dockerfile_inline: |
        FROM openjdk:11-jre
        WORKDIR /
        RUN curl -sOL https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.30.0/opentelemetry-javaagent.jar
    network_mode: host
    volumes:
      - ./example-hello-world-app/target/example-hello-world-app.jar:/example-hello-world-app.jar
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    command:
      - java
      - -javaagent:/opentelemetry-javaagent.jar
      - -jar
      - /example-hello-world-app.jar
  greeting-service:
    # The opentelemetry-java-agent image is coming from the hello-world-up service above.
    image: opentelemetry-java-agent
    network_mode: host
    volumes:
      - ./example-greeting-service/target/example-greeting-service.jar:/example-greeting-service.jar
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    command:
      - java
      - -javaagent:/opentelemetry-javaagent.jar
      - -jar
      - /example-greeting-service.jar
  collector:
    image: otel/opentelemetry-collector-contrib:0.150.1@sha256:a516c26968aa1feb5e5fc0562e3338ea13755cb4f373603226bcc4e276374ad0
    network_mode: host
    volumes:
      - ./config/otelcol-config.yaml:/config.yaml
    command:
      - --config=file:/config.yaml
  prometheus:
    image: prom/prometheus:v3.11.2@sha256:5550dc63da361dc30f6fe02ac0e4dfc736ededfef3c8d12a634db04a67824d78
    network_mode: host
    volumes:
      - ./config/prometheus.yaml:/prometheus.yaml
    command:
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --config.file=/prometheus.yaml
  tempo:
    image: grafana/tempo:2.10.1@sha256:9371af1b75b4e057eb77f22dc4dd4d9176cd6985e29f181527be6723b7f29c41
    network_mode: host
    volumes:
      - ./config/tempo-config.yaml:/config.yaml
    command:
      - --config.file=/config.yaml
  grafana:
    image: grafana/grafana:13.0.1@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
      - ./config/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
      - ./config/grafana-example-dashboard.json:/etc/grafana/example-dashboard.json
  k6:
    image: grafana/k6@sha256:5e937f439684142ba7803722b42e3c9ac9233cfa01d561de0596c1c2794fd680
    network_mode: host
    volumes:
      - ./config/k6-script.js:/k6-script.js
    command:
      - run
      - /k6-script.js
