{
 "title": "Example Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Request Duration 95th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(request_duration_seconds{job=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_count(rate(request_duration_seconds{job=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Traces Ingested in Tempo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(tempo_ingester_traces_created_total[5m])"
    }
   ]
  }
 ]
}