global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "tempo"
    static_configs:
      - targets: ["localhost:3200"]
  - job_name: "hello-world-app"
    static_configs:
      - targets: ["localhost:8080"]
  - job_name: "greeting-service"
    static_configs:
      - targets: ["localhost:8081"]
