[tools]
java = "oracle-graalvm-25.0.1"

[tasks.native-test]
depends = "build"
# Native Test uses Surefire, so explicitly select the Failsafe-named test class.
run = "../../mvnw test -PnativeTest -Dtest=ApplicationIT"
dir = "../../../integration-tests/it-spring-boot-smoke-test"
