---
name: OpenTelemetry Acceptance Tests

on: [pull_request]

permissions: {}

jobs:
  acceptance-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        with:
          persist-credentials: false
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: v2026.4.16
          sha256: 69d321fca47d6ece2924bd95ab2343e3e1c7704d6b6cb5de15e4f753d8c54be1
      - name: Run acceptance tests
        run: mise run acceptance-test
