---
name: OpenTelemetry Acceptance Tests

on: [pull_request]

permissions: {}

jobs:
  acceptance-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        with:
          persist-credentials: false
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          version: v2026.7.5
          sha256: 5f7ab76afdf0780d12edeaa67e908094e9ccf7924cfe203e415c1cfb87bbf778
      - name: Run acceptance tests
        run: mise run acceptance-test
