---
name: GraalVM Native Tests

on: [pull_request]

permissions: {}

jobs:
  native-tests:
    runs-on: ubuntu-26.04
    steps:
      - name: Check out
        with:
          persist-credentials: false
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
        with:
          version: v2026.9.17
          sha256: 63049bc35fb9065e8dc35ac8b25fdae53e9bd6f1885a843aedeba398e046a1ee
      - name: Run native tests
        run: mise run native-test
