---
name: GraalVM Native Tests

on: [pull_request]

permissions: {}

jobs:
  native-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        with:
          persist-credentials: false
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          version: v2026.9.6
          sha256: 04260a49d2cb7f46c91d3f90547f8486ba6c6c9e545b98e69b685cdcf0db8576
      - name: Run native tests
        run: mise run native-test
