---
name: GraalVM Native Tests

on: [pull_request]

permissions: {}

jobs:
  native-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        with:
          persist-credentials: false
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up GraalVM
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: "graalvm"
          java-version: "25.0.1"

      - name: Cache local Maven repository
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-native-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-native-
            ${{ runner.os }}-maven-

      - name: Run native tests
        working-directory: integration-tests/it-spring-boot-smoke-test
        run: ../../mvnw test -PnativeTest
