---
name: PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
permissions: {}

jobs:
  pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read # action-semantic-pull-request reads the PR title
    steps:
      - uses: grafana/shared-workflows/actions/lint-pr-title@70c40e5b6522c854a55334124545261cae3d4c73 # lint-pr-title/v1.2.4
