---
name: Release Please

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    if: ${{ github.repository == 'prometheus/client_java' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/config/release-please-config.json
          manifest-file: .github/config/.release-please-manifest.json

      - name: Trigger deploy to Maven Central
        if: ${{ steps.release-please.outputs.releases_created == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh workflow run release.yml
          -f tag=${{ steps.release-please.outputs.tag_name }}
